AWSTemplateFormatVersion: '2010-09-09'

Description: chalice-workshop

Resources:

  DevTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: users-dev
      AttributeDefinitions:
      - AttributeName: UserName
        AttributeType: S
      KeySchema:
      - AttributeName: UserName
        KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  ProdTable:  
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: users-prod
      AttributeDefinitions:
      - AttributeName: UserName
        AttributeType: S
      KeySchema:
      - AttributeName: UserName
        KeyType: HASH
      BillingMode: PAY_PER_REQUEST
